export type DigistoreIPN = {
  email?: string;
  first_name?: string;
  last_name?: string;
  title?: string;
  salutation?: string; // Herr, Frau
  company?: string;
  street?: string;
  city?: string;
  zipcode?: string;
  state?: string;
  country_code?: string;
  country_name?: string;
  phone_no?: string;
  order_id?: string;
  transaction_id?: string;
  product_name?: string;
  product_name_intern?: string;
  product_id?: string;
  quantity?: string;
  receipt_url?: string;
  invoice_url?: string;
  eticket_url?: string;
  custom?: string;
  tags?: string;
  event?: string;
  event_label?: string;
  amount_brutto?: string;
  amount_netto?: string;
  amount_vendor?: string;
  amount_affiliate?: string;
  currency?: string;
  is_gdpr_country?: string;
  sha256_signature?: string;
};
