name: CI - Build Check

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Add environment variables
        run: |
          cat <<EOF >> .env
          DIRECT_DATABASE_URL=${{ secrets.DIRECT_DATABASE_URL }}
          OPTIMIZE_API_KEY=${{ secrets.OPTIMIZE_API_KEY }}
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          EMAIL_SERVER_USER=${{ secrets.EMAIL_SERVER_USER }}
          EMAIL_SERVER_PASSWORD=${{ secrets.EMAIL_SERVER_PASSWORD }}
          EMAIL_SERVER_HOST=${{ secrets.EMAIL_SERVER_HOST }}
          EMAIL_SERVER_PORT=${{ secrets.EMAIL_SERVER_PORT }}
          EMAIL_FROM=${{ secrets.EMAIL_FROM }}
          META_APP_ID=${{ secrets.META_APP_ID }}
          META_APP_SECRET=${{ secrets.META_APP_SECRET }}
          S3_REGION=${{ secrets.S3_REGION }}
          S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}
          CLOUDFRONT_KEY=${{ secrets.CLOUDFRONT_KEY }}
          CAL_API_KEY=${{ secrets.CAL_API_KEY }}
          COPECART_KEY=${{ secrets.COPECART_KEY }}
          DIGISTORE_KEY=${{ secrets.DIGISTORE_KEY }}
          SPOTIFY_CLIENT_ID=${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET=${{ secrets.SPOTIFY_CLIENT_SECRET }}
          NEXT_PUBLIC_POSTHOG_KEY=${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST=${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }}
          TRACK_API_KEY=${{ secrets.TRACK_API_KEY }}
          EOF

      - name: Run build
        run: npm run build
